name: Terraform Validation
on:
  push:
    branches:
      - [ $default-branch ]
  pull_request:
    branches:
      - [ $default-branch ]

jobs:
  push-container:
    runs-on: ubuntu-latest
    #- name: Test if it gets template
      #runs: echo "works"
    # - name: Dockerize application
    # - runs: docker build

    # - name: Push Docker to docker hub
    #   runs: docker push

